# Generated by Django 3.0.2 on 2020-05-27 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgType', models.PositiveSmallIntegerField(choices=[(1, 'Button'), (2, 'Notify')])),
                ('msgContext', models.CharField(max_length=50)),
                ('button1', models.CharField(default='', max_length=20)),
                ('button2', models.CharField(default='', max_length=20)),
                ('isPLC_ID', models.IntegerField()),
                ('Contact_Type', models.PositiveSmallIntegerField(choices=[(1, 'X'), (2, 'Y'), (3, 'M')])),
                ('author', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
