# Generated by Django 3.0.2 on 2020-02-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('control_type', models.PositiveSmallIntegerField(choices=[(1, 'Button'), (2, 'Toggle Switches'), (3, 'Text'), (4, 'Gauge')])),
                ('isPLC_ID', models.IntegerField()),
                ('Contact_Type', models.PositiveSmallIntegerField(choices=[(1, 'X'), (2, 'Y'), (3, 'M'), (4, 'D')])),
                ('Contact_ID', models.IntegerField()),
            ],
        ),
    ]
