# Generated by Django 3.0.2 on 2020-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200213_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='Text',
            field=models.CharField(default='', max_length=40),
        ),
    ]
