# Generated by Django 3.0.2 on 2020-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_control_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='control',
            name='control_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Button'), (2, 'Toggle Switches'), (3, 'Gauge(Not done yet.)'), (4, 'Green Lamp'), (5, 'Yellow Lamp'), (6, 'Red Lamp'), (7, 'Numerical')]),
        ),
    ]
