# Generated by Django 3.0.2 on 2020-02-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_control_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='author',
        ),
    ]
