# Generated by Django 3.0.2 on 2020-02-27 02:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='device',
            new_name='devices',
        ),
    ]
