# Generated by Django 3.0.2 on 2020-03-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200227_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='last_modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
