# Generated by Django 3.0.2 on 2020-04-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_devices_last_modify_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='devices',
        ),
    ]
