# Generated by Django 3.0.2 on 2020-04-07 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='isplc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('isPLC_ID', models.IntegerField(default=0)),
                ('Xcontact', models.CharField(max_length=6)),
                ('Ycontact', models.CharField(max_length=6)),
                ('Mcontact', models.CharField(max_length=50)),
                ('Dcontact', models.TextField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'isplcs',
            },
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=40)),
                ('device_ID', models.CharField(max_length=40)),
                ('displc_count', models.IntegerField(default=1)),
                ('device_IP', models.GenericIPAddressField()),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
    ]
