# Generated by Django 3.0.2 on 2020-02-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isplcAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isplc',
            name='isPLC_ID',
        ),
    ]
