# Generated by Django 3.0.2 on 2020-04-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isplcAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_ID',
        ),
    ]
