# Generated by Django 3.0.2 on 2020-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isplcAPI', '0002_remove_isplc_isplc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='isplc',
            name='isPLC_ID',
            field=models.IntegerField(default=0),
        ),
    ]
