# Generated by Django 3.0.2 on 2020-02-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isplcAPI', '0003_isplc_isplc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isplc',
            name='Mcontact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='isplc',
            name='Xcontact',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='isplc',
            name='Ycontact',
            field=models.CharField(max_length=6),
        ),
    ]
